### ISSUE TITLE
Not able to download chatgpt backup data

### ISSUE THREAD

**Issue by Ayush4816** [mzbac/chatgpt-backup-extension#1]
Not able to download the backup data from chrome extension, it is giving error "Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist." please help.

**Comment by mzbac** [comment]
It looks like you have a connection issue. Please make sure you are logged into the ChatGPT and that your network is connected.

**Comment by Ayush4816** [comment]
I have followed all the steps mention in the git hub page but getting same issue. Could you please send me the backup.json file to my mail 'ayu.jain4@gmail.com'. 
Thank you.

**Comment by mzbac** [comment]
Unfortunately, I cannot send you my ChatGPT backup. If this doesn't work for you, you can request to export your data backup directly from OpenAI. https://help.openai.com/en/articles/7260999-how-do-i-export-my-chatgpt-history-and-data

**Comment by Ayush4816** [comment]
I don't have data on chatgpt. Can you please help me to provide sample data from backup.json, so that i can prepare my data in similar format. Since I am not aware about the format of the data.
Thanks in advance.

**Comment by mzbac** [comment]
@Ayush4816 
If you are looking for the data format, it is just an array of objects with key-value pairs for questions and answers. For example:
```json
[
  {
    "question": "{your question}",
    "answer": "{your answer}"
  },
]
```

I assume you are trying to do Qlora fine-tuning using the dataset: https://github.com/mzbac/qlora-fine-tune/blob/main/qlora.py#L521-L527

**Comment by Ayush4816** [comment]
Sure Thanks

**Comment by Ayush4816** [comment]
HI Need one help, does the above format will be the final format of input data which has to send to the model for fine tune?
or else kindly provide the final format of the input data.
Thanks in advance.

**Comment by mzbac** [comment]
If you look at the Qlora script on GitHub (https://github.com/mzbac/qlora-fine-tune/blob/main/qlora.py#L521-L527), you can modify the input and output strings according to your model's prompt format. The input and output in the dataset map is the format that will be sent to your model for training.
